spring:
  application:
    name: focus
  datasource:
    url: jdbc:mysql://focus.c94y6cs2sggm.ap-northeast-2.rds.amazonaws.com:3306/Focus
    username: admin
    password: eksrnreogkrry
#    url: jdbc:mysql://localhost:3306/taba
#    username: root
#    password: Eksrnreogkrry1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  security:
#    user:
#      name: user
#      password: 1234


jwt:  #터미널에 openssl rand -hex 32 입력. HS256 알고리즘 사용
  secret: 93f4e4a4f4a16bada44520c35a55b3b57a03e322dc5aa1b540b4f0c5f1ed5d89
